### PR TITLE
Add template for custom script menus

### PR DESCRIPTION
**Pull request by Adex-8x**
- Adds optional support for custom script engine menus
- Updates README.md

### CODE REVIEW

**Comment by Adex-8x** [comment]
Actually, thinking of it, couldn't we do away with the comments in `internal.asm` in favor of `.ifdef`? Like for example:
```arm
  .ifdef HookKeyboardCheck
  .org ShowKeyboard
    push {r3-r8,lr}
    bl HookKeyboardCheck

  .org ShowKeyboardTypeCase3
    b HookKeyboardCustomPrompt

  org ShowKeyboardReturn
    pop {r3-r8,pc}

  .org PreprocessStringFromIdCallsite
    bl CustomPreprocessStringFromId
  .endif
```
And that way, the only way the `.ifdef` would pass is if `HookKeyboardCheck` in `menu_hooks.c` is defined, which would only happen if CUSTOM_SCRIPT_MENUS is 1 in `menus.h`. This could also be done for the custom opcodes.

**Comment by tech-ticks** [comment]
> Actually, thinking of it, couldn't we do away with the comments in `internal.asm` in favor of `.ifdef`? Like for example:
> 
> ```
>   .ifdef HookKeyboardCheck
>   .org ShowKeyboard
>     push {r3-r8,lr}
>     bl HookKeyboardCheck
> 
>   .org ShowKeyboardTypeCase3
>     b HookKeyboardCustomPrompt
> 
>   .org ShowKeyboardReturn
>     pop {r3-r8,pc}
> 
>   .org PreprocessStringFromIdCallsite
>     bl CustomPreprocessStringFromId
>   .endif
> ```
> 
> And that way, the only way the `.ifdef` would pass is if `HookKeyboardCheck` in `menu_hooks.c` is defined, which would only happen if `CUSTOM_SCRIPT_MENUS` is 1 in `menus.h`. This could also be done for the custom opcodes.

Sorry for the very late reply, I was either sick or busy in the last weeks.

Yes, the `.ifdef` trick should work. I think we could even move `CUSTOM_SCRIPT_MENUS` into Makefile and then set the ARMIPS command line flag `-definelabel` to define a pseudo label based on whether the flag is enabled.

**Comment by Adex-8x** [comment]
All I want for Christmaaaaaas is menuuuuuu

**Review by tech-ticks — APPROVED** [review]
Thanks!

**Pull request merged**
